### ISSUE TITLE
[Bug]: App crashing on MacOS 11.7.1

### ISSUE THREAD

**Issue by Vilagamer999** [TagStudioDev/TagStudio#412]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha v9.3.2

### Operating System & Version

MacOS 11.7.1

### Description

The app crashes as soon as I try to start it. I have run the program with debug logging and added the log below.

### Expected Behavior

n/a

### Steps to Reproduce

n/a

### Logs

```
Last login: Wed Aug 28 00:02:54 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
/Applications/TagStudio.app/Contents/MacOS/tagstudio ; exit;
users-MacBook-Pro:~ user$ /Applications/TagStudio.app/Contents/MacOS/tagstudio ; exit;
Traceback (most recent call last):
  File "tag_studio.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "src/cli/ts_cli.py", line 23, in <module>
  File "/Applications/TagStudio.app/Contents/Frameworks/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Applications/TagStudio.app/Contents/Frameworks/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib/__init__.py", line 90, in import_module
    
ImportError: dlopen(/Applications/TagStudio.app/Contents/Resources/cv2/cv2.abi3.so, 2): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
  Referenced from: /Applications/TagStudio.app/Contents/Frameworks/cv2/__dot__dylibs/../../libvmaf.1.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

[55874] Failed to execute script 'tag_studio' due to unhandled exception: dlopen(/Applications/TagStudio.app/Contents/Resources/cv2/cv2.abi3.so, 2): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
  Referenced from: /Applications/TagStudio.app/Contents/Frameworks/cv2/__dot__dylibs/../../libvmaf.1.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

[55874] Traceback:
Traceback (most recent call last):
  File "tag_studio.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "src/cli/ts_cli.py", line 23, in <module>
    import cv2
  File "/Applications/TagStudio.app/Contents/Frameworks/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Applications/TagStudio.app/Contents/Frameworks/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib/__init__.py", line 90, in import_module
ImportError: dlopen(/Applications/TagStudio.app/Contents/Resources/cv2/cv2.abi3.so, 2): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
  Referenced from: /Applications/TagStudio.app/Contents/Frameworks/cv2/__dot__dylibs/../../libvmaf.1.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib


logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...3 completed.

[Process completed]
```

**Comment by CyanVoxel** [comment]
This seems to be an issue with the version of `cv2` we're using, which only supports macOS 12+. This is also the range of macOS versions we've been "officially" supporting, but we'll have a look into whether or not switching to an older version of `cv2` would be an easy fix to add macOS 11 compatibility for the foreseeable future.

**Comment by Vilagamer999** [comment]
That makes sense, I'm currently on a 2015 macbook pro and decided to not upgrade past macos 12 because that's when apple messed up a lot of things in terms of design, functionality and reliability. I'll have to upgrade eventually since I'm finding that a lot of software nowadays requires macos 12 or older. (unlike with windows were to this day you can still run windows 3.1 software on windows 11)

I'd be nice if maybe there was a version for older macos systems.

**Comment by CyanVoxel** [comment]
Unfortunately we're not able to build releases for macOS 11 or even macOS 12 anymore, so I'll have to close this. [Building yourself](https://docs.tagstud.io/install/#building) is always an option, however you would need to downgrade the versions of some of our dependencies (i.e.`opencv_python`) to ones that are compatible with your OS version, assuming they would still work. We also now allow for [installing with PIP](https://docs.tagstud.io/install/#installing-with-pip), however the same dependency issues apply.
